version: '3.7'

services:
  mongo:
    container_name: tera_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb:/data/db"
    networks:
      - mongo-els
  
  mongo-express:
    container_name: tera_mongo_express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: express
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: tera_mongo
    depends_on:
      - mongo
    networks:
      - mongo-els

  elasticsearch:
    container_name: tera_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - ./esdata:/usr/share/elasticsearch/data:rw
    environment:
      cluster.name: "docker-cluster"
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - mongo-els

  kibana:
    container_name: tera_kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks: 
      - mongo-els


networks:
  mongo-els:
    driver: bridge    
volumes:
  mongodb:
  esdata: