version: '3.7'

services:
  mongo:
    container_name: tera_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb:/data/db"
    networks:
      - mongo-els
  
  mongo-express:
    container_name: tera_mongo_express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: express
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: tera_mongo
    depends_on:
      - mongo
    networks:
      - mongo-els

  
networks:
  mongo-els:
    name: mongo-els
        
volumes:
  mongodb:
  